version: '3'

# 학습 기준 mariaDb 사용
# Usage: docker-compose -f ./docker-compose.yml -f ./docker-compose-postgres.yml up
services:

  mariadb:
    image: public.ecr.aws/docker/library/mariadb:10-focal
    container_name: dataflow-mariadb
    environment:
      LANG: ko.KR-utf8
      LC_ALL: ko_KR.utf8
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - 3306
    ports:
      - '3306:3306'
    platform: linux/amd64

  dataflow-server:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${DATABASE_DRIVER_CLASS_NAME}
    depends_on:
      - mariadb

  skipper-server:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${DATABASE_DRIVER_CLASS_NAME}
    depends_on:
      - mariadb
