version: '3'

# 학습 기준 mariaDb 사용
# Usage: docker-compose -f ./docker-compose.yml -f ./docker-compose-postgres.yml up
services:
  dataflow-server:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${DATABASE_DRIVER_CLASS_NAME}

